# Generated by Django 4.2.5 on 2025-01-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='guidelines',
            field=models.TextField(blank=True, null=True),
        ),
    ]
